name: Demo-Test-Build

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    with:
      mvnArgs: -pl demo/smart-workflow-supplier-demo-test -am -P demo.test
      javaVersion: 25
      cspellExtraWords: .github/cspell-extra-words.txt
