name: IT-Build

on:
  schedule:
    - cron: '0 1 * * *' # 1 AM every night
  workflow_dispatch:
    inputs:
      ivyVersion:
        type: string
        required: false
        default: dev
        description: ivy engine permalink (e.g. sprint, nightly, dev)

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    with:
      mvnArgs: -P container.test
      javaVersion: 25
      cspellExtraWords: .github/cspell-extra-words.txt
      ivyVersion: ${{ inputs.ivyVersion || 'dev' }}
